version: 0.0
os: linux
files:
   - source: /
     destination: /usr/share/nginx/html/
permissions:
   - object: /usr/share/nginx/html/
     pattern: "**"
     owner: apache
     group: apache
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/install_dependencies
      runas: root
    - location: scripts/start_server
      runas: root
   AfterInstall:
    - location: scripts/stop_server
      runas: root
