version: 0.0
os: linux
files:
	– source: /index.html
	  destination: /usr/share/nginx/html/
hooks:
	BeforeInstall:
	  – location: scripts/install_dependencies.sh
	  runas: root
	  – location: scripts/start_server.sh
  	  runas: root
	  ApplicationStop:
	  – location: scripts/stop_server.sh
          runas: root
