version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo env init
  build:
    commands:
      - echo Building the Go code...
      - "chmod +x ./build.sh"
      - "./build.sh"
      - ls -lart
  post_build:
    commands:
      - aws s3 sync build/ s3://$S3_BUCKET
# artifacts:
#   secondary-artifacts:
#     golang_artifacts:
#       base-directory: golang-app
#       files:
#         - hello
#     nodejs_artifacts:
#       base-directory: nodejs-app
#       files:
#         - index.js
#         - package.json
